### ISSUE TITLE
Create filter control objects

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/cherry_blossom_tracker#34]
Code two dropdowns (Neighbourhood and Cultivar) a Date control (Bloom period) and a slider (diameter) control for use in each visual.

**Comment by showcy** [comment]
During my configuration of the timeline, I feel that might be better to change the month to range slider rather than using the dropdown menu because the start and end date varies.

@gfairbro @ytz @katerinkus

**Comment by gfairbro** [comment]
I think the original idea was to create a calendar selector to choose a range, which you can then use to populate the Gantt Chart and we can filter the other visuals where appropriate as well.

**Comment by showcy** [comment]
> I think the original idea was to create a calendar selector to choose a range, which you can then use to populate the Gantt Chart and we can filter the other visuals where appropriate as well.

Ok. Change it to a date picker. Please check.
