### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by katerinkus** [UBC-MDS/cherry_blossom_tracker#54]
- [x] Create issue for our group [here](https://github.com/UBC-MDS/DSCI532-peer-review/issues)

**Comment by ytz** [comment]
I have created an [issue](https://github.com/UBC-MDS/DSCI532-peer-review/issues/4) for our group

**Comment by showcy** [comment]
Thans TZ.

So we just need one final review to Group 26, correct?

**Comment by katerinkus** [comment]
Here is the link to our peer review:
https://github.com/UBC-MDS/DSCI532-peer-review/issues/29
