### ISSUE TITLE
Add average in the tree diameters plot or in the tooltip of tree density map

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/cherry_blossom_tracker#67]
Please include your commit link in the issue, so that it is easier for me to collate and submit

**Comment by ytz** [comment]
Density map: 9bd842788abc9c291aae55a6ab7d33fb3a99e224

**Comment by katerinkus** [comment]
I have unsuccessfully tried to add the tool tip. I don't think it makes sense in the context of density so nothing shows up. I tried several methods: your method, Florencia's method and my method.
