### ISSUE TITLE
Change color of 'loader/spinner' to fit theme (see lecture)

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/cherry_blossom_tracker#68]
Please include your commit link in the issue, so that it is easier for me to collate and submit

**Comment by ytz** [comment]
#72

**Comment by showcy** [comment]
https://github.com/UBC-MDS/cherry_blossom_tracker/pull/72/commits/68bb5412a23e3972b6d2c2f28d74f2d9f4a13ada
