### ISSUE TITLE
Multi-selection in the filters

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/cherry_blossom_tracker#69]
Please include your commit link in the issue, so that it is easier for me to collate and submit

**Comment by showcy** [comment]
Commit from PR: https://github.com/UBC-MDS/cherry_blossom_tracker/pull/72/commits/3a19f8925ae9d19a5832a31aca9d2b8ef3349add

**Comment by showcy** [comment]
Please add this improvement as well.

https://github.com/UBC-MDS/cherry_blossom_tracker/pull/73/commits

"Make filters clearable and searchable and make date picker clearable."
