### ISSUE TITLE
Description of your app & sketch

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/cherry_blossom_tracker#8]
Building from your research questions and usage scenarios, give a high-level description of the interface for the app you will build. Remember to be realistic about your expectations and plans since you will actually be implementing this app (but again, you will not be penalized if you need to adjust a bit in later milestones). It is better to design a slightly more limited app that you have time to implement well, instead of a complicated app that you don’t have time to finish. At the same time, you cannot just make a single barchart and call it a day. The app needs to have a few plot panels, use the visualizations from previous students as a guide as a complexity target for the final app.

In this description you are not required to use terminology specific to Dash apps (i.e. widgets, components, etc…) or make reference to specific Python or R libraries. Your sketch can be hand-drawn or mocked up using a graphics editor. If you can show the app visual design & interaction design in a single image that is ideal, but if you need more space to show some other planned features of your app you can include max three images for this proposal.

The description should be about 200-300 words and live in the README.md file of your GitHub.com repository. The sketch should be linked in the README.md file of your GitHub.com repository underneath the high level description so that the image shows up on GitHub.

- [x] Description of app
- [x] Sketch

[Figma link](https://www.figma.com/file/mKaPCKS93DpiFmW1zts9pC/Test-mockup-(Copy)?node-id=3%3A86)

**Comment by ytz** [comment]
![Screen Shot 2022-02-15 at 9 53 24 PM](https://user-images.githubusercontent.com/1884616/154204715-e716f411-c07e-4672-a52a-de9e2871cd57.png)

Sketched out a super rough idea. You can also comment on Figma itself [here](https://www.figma.com/file/mKaPCKS93DpiFmW1zts9pC/Test-mockup-(Copy)?node-id=101%3A94)

**Comment by katerinkus** [comment]
Cool! It is very similar to my idea but somewhat different. The map is not as prominent on mine but I like it on yours, too.
Please checkout my prototype [here](https://www.figma.com/proto/wL64Jd85dE2p9KtgRm4SHr/Katia's-mockup?node-id=3%3A86&scaling=scale-down&page-id=0%3A1).


![image](https://user-images.githubusercontent.com/8015482/154624414-a4e95d0d-6eb8-4993-862c-d32c88c4d0ab.png)

**Comment by ytz** [comment]
Looks great, love the color scheme! @showcy @gfairbro, any thoughts/comments?

**Comment by katerinkus** [comment]
I agree, the map should be more prominent. So do you think we should have both the navigation at the top and a side bar?

**Comment by ytz** [comment]
I kinda feel that having both top and side bar is excessive. But I think I'll leave the design stuff to @katerinkus haha. Any suggestions on where to place some descriptive text? 

I saw a group from previous year have a button that will expand (see below). That is one option.
![myfile](https://camo.githubusercontent.com/78a77e0c2028d6e95123b24f6c7dbd0aae625014fa9ca403900c21920a86c84a/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f674177465a75455363336c71703954576e632f67697068792e676966)

**Comment by katerinkus** [comment]
I like this! It can be a `div` that appears on a click when you select `About`. Or it can be a button`?` in the corner that kind of always stays (so it does not scroll but is always in the corner).

As for the map, I think it will be nice to have an option to make the map either full view or not full view. So it can be half of the screen on desktop but can become a wider view (like videos on youtube). On mobile it will be one by one (map, plot, etc) since there is not enough space width-wise.
